title: Charles' Documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

plugins:
  - jekyll-default-layout


url: https://github.com/CJensenUalberta

aux_links:
  My Repositories: https://github.com/CJensenUalberta
  

